version: '3'

services:
  xgl:
    container_name: xgl
    hostname: xgl
    image: ghcr.io/4minus1d/vastai-docker-nvidia-glx-desktop:latest
    runtime: nvidia
    ports:
      - '8080:8080'
      - '3478:3478'
      - '3478:3478/udp'
      - '65534-65535:65534-65535'
      - '65534-65535:65534-65535/udp'
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tmpfs:
      - '/dev/shm:rw'
    environment:
      TZ: UTC
      DISPLAY_SIZEW: 1920
      DISPLAY_SIZEH: 1080
      DISPLAY_REFRESH: 60
      DISPLAY_DPI: 96
      DISPLAY_CDEPTH: 24
      VIDEO_PORT: DFP
      PASSWD: mypasswd
      SELKIES_ENCODER: nvh264enc
      SELKIES_ENABLE_RESIZE: false
      SELKIES_VIDEO_BITRATE: 8000
      SELKIES_FRAMERATE: 60
      SELKIES_AUDIO_BITRATE: 128000
      SELKIES_ENABLE_BASIC_AUTH: true
      SELKIES_ENABLE_HTTPS: false
      SELKIES_TURN_HOST: turnserver
      SELKIES_TURN_PORT: 3478
      SELKIES_TURN_PROTOCOL: udp
      SELKIES_TURN_TLS: false
      TURN_MIN_PORT: 65534
      TURN_MAX_PORT: 65535
      SELKIES_TURN_SHARED_SECRET: n0TaRealCoTURNAuthSecretThatIsSixtyFourLengthsLongPlaceholdPlace

  turnserver:
    image: coturn/coturn
    container_name: turnserver
    ports:
      - '3478:3478'
      - '3478:3478/udp'
      - '5349:5349'
      - '5349:5349/udp'
    environment:
      TURN_MIN_PORT: 49152
      TURN_MAX_PORT: 65535
      EXTERNAL_IP: turnserver
      LISTENING_PORT: 3478
      RELAY_IP: turnserver
      AUTH_SECRET: n0TaRealCoTURNAuthSecretThatIsSixtyFourLengthsLongPlaceholdPlace
