apiVersion: apps/v1
kind: Deployment
metadata:
  name: xgl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xgl
  template:
    metadata:
      labels:
        app: xgl
    spec:
      hostname: xgl
      containers:
      - name: xgl
        image: ehfd/nvidia-glx-desktop:latest
        env:
        - name: TZ
          value: "UTC"
        - name: SIZEW
          value: "1920"
        - name: SIZEH
          value: "1080"
        - name: CDEPTH
          value: "24"
        - name: SHARED
          value: "TRUE"
        - name: VNCPASS
          value: "vncpasswd"
#          valueFrom:
#            secretKeyRef:
#              name: xgl-pass
#              key: xgl-pass
        - name: VIDEO_PORT
          value: "DFP"
        stdin: true
        tty: true
        ports:
        - containerPort: 5901
          protocol: TCP
        resources:
          limits:
            memory: 64Gi
            cpu: "16"
            nvidia.com/gpu: 1
# Deploy either https://gitlab.com/arm-research/smarter/smarter-device-manager or https://github.com/bluebeach/k8s-hostdev-plugin and increase allocatable resources of one same virtual terminal device to at least the number of GPUs
#            smarter-devices/tty63: 1
#            hostdev.k8s.io/dev_tty63: 1
          requests:
            memory: 100Mi
            cpu: 100m
        volumeMounts:
        - mountPath: /cache
          name: xgl-cache-vol
        - mountPath: /home/user
          name: xgl-root-vol
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: xgl-cache-vol
        emptyDir: {}
#        persistentVolumeClaim:
#          claimName: xgl-cache-vol
      - name: xgl-root-vol
        emptyDir: {}
#        persistentVolumeClaim:
#          claimName: xgl-root-vol
      - name: dshm
        emptyDir:
          medium: Memory
